'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class InputDataByDate

    '''<summary>
    '''txt_teamID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_teamID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''btn_ExportXlsTemp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_ExportXlsTemp As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''lbl_temp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_temp As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''file_importPartiData control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents file_importPartiData As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btn_import control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_import As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''gv_matchDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_matchDetail As Global.DevExpress.Web.ASPxGridView
End Class
