'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OverviewPage

    '''<summary>
    '''txt_leagueID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_leagueID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''txt_teamID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_teamID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lbl_league control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_league As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cbb_league control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbb_league As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ods_cbbleague control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_cbbleague As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lbl_team control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_team As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cbb_team control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbb_team As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ods_cbbteam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_cbbteam As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''gv_matchDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_matchDetail As Global.DevExpress.Web.ASPxGridView
End Class
