'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class SettingMasterTable

    '''<summary>
    '''lbl_leagueTable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_leagueTable As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''gv_league control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_league As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ods_leagueMaster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_leagueMaster As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''txt_leagueID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_leagueID As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''lbl_league control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_league As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''cbb_league control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbb_league As Global.DevExpress.Web.ASPxComboBox

    '''<summary>
    '''ods_cbbleague control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_cbbleague As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lbl_teamtable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_teamtable As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''gv_team control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_team As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''lbl_addTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_addTeam As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''txt_addTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txt_addTeam As Global.DevExpress.Web.ASPxTextBox

    '''<summary>
    '''btn_addTeam control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn_addTeam As Global.DevExpress.Web.ASPxButton

    '''<summary>
    '''ods_team control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_team As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lbl_matchpro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_matchpro As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''gv_matchpro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_matchpro As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ods_matchpro control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_matchpro As Global.System.Web.UI.WebControls.ObjectDataSource

    '''<summary>
    '''lbl_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_location As Global.DevExpress.Web.ASPxLabel

    '''<summary>
    '''gv_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gv_location As Global.DevExpress.Web.ASPxGridView

    '''<summary>
    '''ods_location control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ods_location As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
